### ISSUE TITLE
Performance compared to existing models

### ISSUE THREAD

**Issue by j-min** [dsindex/segm-lstm#1]
Could you please explain if this LSTM-based model can outperform conventional CRF-based models? (Accuracy or Speed..)

**Comment by dsindex** [comment]
@j-min 

the LSTM-based model is just a toy example and i don't have enough evidences to conclude. 
but, if a CRF-based model uses same features, then it is probably less accurate because LSTM model itself is slightly better than CRF. however,  if i am asked to develop a auto-space module, i would not use a LSTM-based model but use a CRF-based model. 

i like to develop a module which is well suite for normal web servers not equipped with GPUs. and there are a lot of products and papers about the auto-spacing problem which already reach desired accuracy and speed.      

i believe applying 'Appropriate Technology' is always good!

**Comment by j-min** [comment]
Thanks for reply!
